// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egrypamzqgbwqapapwwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVncnlwYW16cWdid3FhcGFwd3diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MzI0MjYsImV4cCI6MjA2NDIwODQyNn0.LAgTJdHLwiON8RC64pF2VHJWnuh7HaobsTDdhao1MO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);